services:
  postgres:
    image: postgres:17
    container_name: horizon-postgres
    environment:
      POSTGRES_DB: horizon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    image: horizon/backend:latest
    container_name: horizon-backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/horizon_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ${JWT_SECRET}
      GITHUB_TOKEN: ${GITHUB_TOKEN}

  frontend:
    build: ../../fronend
    image: horizon/fronend:latest
    container_name: horizon-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data: